using System;
using System.Collections.Generic;
using System.Text;

namespace AxisAndAllies3.Models.Land
{
    public enum Territories
    {
        ALASKA, ALGERIA, ANGLO_EGYPT_SUDAN,ARGENTINA_CHILI, AUSTRALIA, BELGIAN_CONGO, BORNEO_CELEBES, BRAZIL, CAROLINE_ISLANDS, CAUCASUS, CHINA, EASTERN_CANADA, EASTERN_EUROPE, EASTERN_USA, EAST_INDIES, EGYPT, EIRE, EVENKINATLOKRUG, FINLAND_NORWAY, FRENCH_EQUATORIAL_AFRICA, FRENCH_INDO_CHINA_BURMA, FRENCH_MADAGASCAR, FRENCH_WEST_AFRICA, GERMANY, GIBRALTAR, HAWAIIAN_ISLANDS, INDIA, ITALIAN_EAST_AFRICA, JAPAN, KARELIA_SSR, KAZAKH_SSR, RHODESIA, KWANGTUNG, LIBYA, MANCHURIA, MEXICO, MIDWAY_ISLAND, MONGOLIA, MOROCCO, MOZAMBIQUE, NEW_GUINEA, NEW_ZEALAND, NOVOSIBIRSK, OKINAWA, PANAMA, PERSIA, PERU, PHILIPPINE_ISLANDS, RIO_DE_ORO, RUSSIA, SAUDI_ARABIA, SINKIANG, SOLOMON_ISLANDS, SOUTHERN_EUROPE, SOVIET_FAR_EAST, SPAIN, SWEDEN, SWITZ, SYRIA_IRAQ, TURKEY, UKRAINE, UNION_OF_SOUTH_AFRICA, UNITED_KINGDOM, VENEZUELA_COLUMBIA, WAKE_ISLAND, WESTERN_CANADA, WESTERN_EUROPE, WESTERN_USA, WEST_INDIES, YAKUT_SSR,
        SZ_1, SZ_2, SZ_3, SZ_4, SZ_5, SZ_6, SZ_7, SZ_8, SZ_9, SZ_10, SZ_11, SZ_12, SZ_13, SZ_14, SZ_15, SZ_16, SZ_17, SZ_18, SZ_19, SZ_20, SZ_21, SZ_22, SZ_23, SZ_24, SZ_25, SZ_26, SZ_27, SZ_28, SZ_29, SZ_30, SZ_31, SZ_32, SZ_33, SZ_34, SZ_35, SZ_36, SZ_37, SZ_38, SZ_39, SZ_40, SZ_41, SZ_42, SZ_43, SZ_44, SZ_45, SZ_46, SZ_47, SZ_48, SZ_49, SZ_50, SZ_51, SZ_52, SZ_53, SZ_54, SZ_55, SZ_56, SZ_57, SZ_58, SZ_59, SZ_60, SZ_61, SZ_62, SZ_63, SZ_64, SZ_65
    }
}
